spring:
  application:
    name: shoppal

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/shoppal
    username: shoppal_user
    password: vG79xAe3bybahOUIvScJ41KoWsqrYHSr
    driver-class-name: org.postgresql.Driver


    
